# Generated by Django 4.2.25 on 2025-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_code', models.CharField(max_length=10, unique=True)),
                ('given_name', models.CharField(max_length=25)),
                ('family_name', models.CharField(max_length=20)),
                ('books_out', models.IntegerField(default=0)),
            ],
        ),
    ]
