# Generated by Django 4.2.25 on 2025-11-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('loan_number', models.AutoField(primary_key=True, serialize=False)),
                ('borrowed_on', models.DateTimeField(auto_now_add=True)),
                ('book_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_borrowed', to='lib.book')),
                ('borrower_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_borrowing', to='lib.borrower')),
            ],
        ),
    ]
